#!/usr/bin/env perl
use strict;
use warnings;

use lib qw(..);

use JSON qw( );

my($filename) = 'thaicards.json';

my($json_text) = do {
    open(my $json_fh, "<:encoding(UTF-8)", $filename)
        or die("Can't open \$filename\": $!\n");
    local $/;
    <$json_fh>
};

my($card_template) = join("", `cat thaicard.tex.in`);

my($json) = JSON->new;
my($cards) = $json->decode($json_text);

my($index) = 1;
for ( @{$cards->{cards}} ) {
    my($topic) = $_->{topic};
    my($russian) = $_->{russian};
    my($transcript) = $_->{transcript};
    my($thai) = $_->{thai};

    # Parsing accents to colorize them.
    $russian =~ s/'(\w)/\\textcolor{red}{\\'$1}/g;

    my($card) = $card_template;
    $card =~ s/#TOPIC#/$topic/;
    $card =~ s/#RUSSIAN#/$russian/;
    $card =~ s/#TRANSCRIPT#/$transcript/;
    $card =~ s/#THAI#/$thai/;

    my($card_filename) = sprintf("thaicard_%003d", $index);
    open my $fh, ">", "$card_filename.tex" or die("Could not open file. $!");
    print $fh $card;
    close $fh;

    system("xelatex $card_filename.tex");
    system("xelatex $card_filename.tex");
    system("rm $card_filename.tex");
    system("rm $card_filename.aux");
    system("rm $card_filename.log"); 
    system("rm $card_filename.out");

    $index++; 
}

